# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  codecov: codecov/codecov@1.2.3 

executors:
  build:
    resource_class: medium
    macos:
      xcode: "12.5.1"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

  classic:
    machine:
      image: circleci/classic:201808-01

commands:
  git_clone:
    steps:
      - checkout
      - run: 
          name: Checkout git submodules
          command: |
            git submodule sync
            git submodule update --init

  setup_gems:
    steps:
      - restore_cache:
          name: Restoring gems cache
          key: v2-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          name: Saving gems cache
          key: v2-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
  
  setup_pods:
    steps:
      - restore_cache:
          name: Restoring pod cache
          key: v1-pod-{{ checksum "Podfile.lock" }}
      - run:
          name: Pod install
          command: bundle exec pod install --verbose
      - save_cache:
          name: Saving pod cache
          key: v1-pod-{{ checksum "Podfile.lock" }}
          paths: Pods

jobs:
  build:
    executor:
      name: build
    steps:
      - git_clone
      - run:
          name: Build frameworks
          command: |
            DEVICE=`echo ${BUILD_TARGET_DEVICE} | sed 's/_/ /g'`
            OS=`echo ${BUILD_TARGET_OS} | sed 's/_/\./g'`
            xcodebuild -workspace Karte.xcworkspace \
                       -scheme Build \
                       -destination "platform=iOS Simulator,name=${DEVICE},OS=${OS}" \
                       -derivedDataPath DerivedData
      - persist_to_workspace:
          root: DerivedData
          paths:
            - "**/*"
      - slack/status:
          fail_only: true
          
  test:
    executor:
      name: build
    steps:
      - git_clone
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Setup Derived directory
          command: |
            mkdir DerivedData
            cp -r /tmp/workspace DerivedData
      - setup_gems
      - setup_pods
      - run:
          name: Podspec lint
          command: bundle exec pod spec lint *.podspec --quick
      - run:
          name: Run tests
          command: |
            DEVICE=`echo ${BUILD_TARGET_DEVICE} | sed 's/_/ /g'`
            OS=`echo ${BUILD_TARGET_OS} | sed 's/_/\./g'`
            xcodebuild test -workspace Karte.xcworkspace \
                            -scheme KarteTests \
                            -destination "platform=iOS Simulator,name=${DEVICE},OS=${OS}" \
                            -derivedDataPath DerivedData \
                            -resultBundlePath "output/KarteTests_${BUILD_TARGET_DEVICE}_${BUILD_TARGET_OS}.xcresult"
            bundle exec slather
      - codecov/upload:
          xtra_args: -f ./cobertura.xml -X coveragepy -X gcov -X xcode -build_directory "output/KarteTests_${BUILD_TARGET_DEVICE}_${BUILD_TARGET_OS}.xcresult"
          validate_url: true
          
      - run:
          name: Archive test result
          command: zip -r "KarteTests-results.zip" "KarteTests_${BUILD_TARGET_DEVICE}_${BUILD_TARGET_OS}.xcresult"
          working_directory: /Users/distiller/project/output
          when: always
      - store_artifacts:
          path: "output/KarteTests-results.zip"
      - slack/status:
          fail_only: true

  ui_test:
    executor:
      name: build
    steps:
      - run:
          name: Request Ui Test
          command: |
            if [ $EXEC_ENV = 'private' ]; then
              curl -f -u ${CIRCLECI_KEY} \
                    -d build_parameters[CIRCLE_JOB]=e2e_test \
                    -d build_parameters[RELEASE_BRANCH]=${CIRCLE_BRANCH} \
                    ${UI_TEST_ENDPOINT}
            fi

  spm_test:
    executor:
      name: build
    steps:
      - run:
          name: Request Swift-PM link Test
          command: |
            if [ $EXEC_ENV = 'private' ]; then
              curl -f -u ${CIRCLECI_KEY} \
                    -d build_parameters[CIRCLE_JOB]=spm_link_test \
                    ${UI_TEST_ENDPOINT}
            fi

  generate_docs:
    executor:
      name: build
    steps:
      - git_clone
      - setup_gems
      - run:
          name: Generate docs
          command: |
            if [ $EXEC_ENV = 'private' ]; then
              git config --global user.name "${GITHUB_USER_NAME}"
              git config --global user.email "${GITHUB_USER_EMAIL}"
              bundle exec ruby ./generate_docs.rb
            fi
          working_directory: /Users/distiller/project/scripts
      - slack/status:
          fail_only: true

  publish:
    executor:
      name: build
    steps:
      - git_clone
      - setup_gems
      - setup_pods
      - run:
          name: Publish
          command: bash ./scripts/publish.sh
      - slack/status:
          fail_only: true

  publish_pods:
    executor:
      name: build
    steps:
      - git_clone
      - setup_gems
      - setup_pods
      - run:
          name: Publish Pods
          command: bash ./scripts/publish.sh
          environment:
            PODSPEC_ONLY: 1
      - slack/status:
          fail_only: true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - generate_docs:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
      - ui_test:
          filters:
            branches:
              only:
                - develop
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - spm_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
